POST http://localhost:4001/auth/login
Content-Type: application/json

{
	"userTag": "authTest",
	"password": "123456789!"
}

###

POST http://localhost:4001/auth/refresh
Content-Type: application/json

{
	"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOiI2NTYxMTY5YjdmZTdmMDBiZDU2MzRlZTUiLCJ0eXBlIjoicmVmcmVzaCIsInVzZXJUYWciOiJhdXRoVGVzdCIsInVzZXJuYW1lIjoiYXV0aFRlc3QiLCJpYXQiOjE3MDA5OTkzMTN9.vprak5t5Z6_Hk_WoeXsLHGT67emstSq-tThK4teCLtY"
}

###

POST http://localhost:4001/auth/logout
Content-Type: application/json

{
	"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOiI2NTYxMTY5YjdmZTdmMDBiZDU2MzRlZTUiLCJ0eXBlIjoicmVmcmVzaCIsInVzZXJUYWciOiJhdXRoVGVzdCIsImlhdCI6MTcwMDk5Nzg3OX0.9qXeEeI8Ej_RNigKSRJCxO8tDcuy2clIULMjOSfYeTY"
}


###

POST http://localhost:4000/users/getSensitiveData
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOiI2NTYxMTY5YjdmZTdmMDBiZDU2MzRlZTUiLCJ0eXBlIjoicmVmcmVzaCIsInVzZXJUYWciOiJhdXRoVGVzdCIsImlhdCI6MTcwMDk5Nzg4OCwiZXhwIjoxNzAwOTk3OTA4fQ.Fcs6UWQd3a_hn51pVmwFXIp1Nr-LygWfWMjvsZHrbWw


